/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Profile;
import validation.Validation;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author akshatajadhav
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    Profile profile;
    
    public CreateJPanel(Profile profile) {
        initComponents();
        this.profile = profile;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblAddress1 = new javax.swing.JLabel();
        lblMedicalNo = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        lblHealthNo = new javax.swing.JLabel();
        lblLicense = new javax.swing.JLabel();
        lblBankNo = new javax.swing.JLabel();
        lblDeviceSerialNumber = new javax.swing.JLabel();
        lblDeviceId = new javax.swing.JLabel();
        lblDateofBirth = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        lblFax = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblLinkedin = new javax.swing.JLabel();
        lblIp = new javax.swing.JLabel();
        lblFingerPrint = new javax.swing.JLabel();
        lblUniqueID = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtDateofBirth = new javax.swing.JTextField();
        txtAddress1 = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        txtphoneNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtBankno = new javax.swing.JTextField();
        txtSsn = new javax.swing.JTextField();
        txtHealthno = new javax.swing.JTextField();
        txtVehicleIdentificationNumber = new javax.swing.JTextField();
        txtDeviceSerialNumber = new javax.swing.JTextField();
        txtLinkedin = new javax.swing.JTextField();
        txtMedicalno = new javax.swing.JTextField();
        txtDeviceID = new javax.swing.JTextField();
        txtIP = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblGeoData = new javax.swing.JLabel();
        txtAddress2 = new javax.swing.JTextField();
        lblAddress2 = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        lblZip = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        lblBirthCertificate = new javax.swing.JLabel();
        txtLicense = new javax.swing.JTextField();
        txtBirthCertificate = new javax.swing.JTextField();
        lblVehicleIdentificationNumber = new javax.swing.JLabel();
        lblVehicleLicensePlate = new javax.swing.JLabel();
        txtVehicleLicensePlate = new javax.swing.JTextField();
        txtUniqueNumber = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txtContactInfo = new javax.swing.JLabel();
        lblPersonalDetails = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDeviceDetails = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addPhoto = new javax.swing.JButton();
        addFingerprints = new javax.swing.JButton();
        lblIp1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(1000, 800));

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("                                Name :");

        lblAddress1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAddress1.setText("Address Line 1 :");

        lblMedicalNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedicalNo.setText("Medical Record Number :");

        lblSsn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSsn.setText("Social Security Number :");

        lblHealthNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHealthNo.setText("Health Plan Beneficiary Number :");

        lblLicense.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLicense.setText("Driver's license Number :");

        lblBankNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBankNo.setText("Bank Account Number :");

        lblDeviceSerialNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDeviceSerialNumber.setText("Device Serial Number :");

        lblDeviceId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDeviceId.setText("Device ID :");

        lblDateofBirth.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDateofBirth.setText("Date of Birth :");

        lblNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumber.setText("Phone number :");

        lblFax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFax.setText("Fax Number :");

        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("Email Address :");

        lblLinkedin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLinkedin.setText("LinkedIn Profile :");

        lblIp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIp.setText("Photo:");

        lblFingerPrint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFingerPrint.setText("Fingerprint  :");

        lblUniqueID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUniqueID.setText("Unique Identification Number :");

        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtDateofBirth.setForeground(new java.awt.Color(204, 204, 204));
        txtDateofBirth.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDateofBirth.setText("format: MM/DD/YYYY");
        txtDateofBirth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDateofBirthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDateofBirthFocusLost(evt);
            }
        });
        txtDateofBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateofBirthActionPerformed(evt);
            }
        });

        txtAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddress1ActionPerformed(evt);
            }
        });

        txtFax.setForeground(new java.awt.Color(204, 204, 204));
        txtFax.setText("format: (xxx)xxx-xxxx");
        txtFax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFaxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFaxFocusLost(evt);
            }
        });
        txtFax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxActionPerformed(evt);
            }
        });

        txtphoneNumber.setForeground(new java.awt.Color(204, 204, 204));
        txtphoneNumber.setText("format: (xxx)xxx-xxxx");
        txtphoneNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtphoneNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtphoneNumberFocusLost(evt);
            }
        });
        txtphoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneNumberActionPerformed(evt);
            }
        });
        txtphoneNumber.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtphoneNumberPropertyChange(evt);
            }
        });
        txtphoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtphoneNumberKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtphoneNumberKeyTyped(evt);
            }
        });

        txtEmail.setForeground(new java.awt.Color(204, 204, 204));
        txtEmail.setText("example: example@gmail.com");
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtBankno.setForeground(new java.awt.Color(204, 204, 204));
        txtBankno.setText("format: 10-13 digits");
        txtBankno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBanknoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBanknoFocusLost(evt);
            }
        });

        txtSsn.setForeground(new java.awt.Color(204, 204, 204));
        txtSsn.setText("format: XXX-XX-XXXX");
        txtSsn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSsnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSsnFocusLost(evt);
            }
        });
        txtSsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSsnActionPerformed(evt);
            }
        });

        txtHealthno.setForeground(new java.awt.Color(204, 204, 204));
        txtHealthno.setText("format: xxxx-xxx-xxxx");
        txtHealthno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHealthnoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHealthnoFocusLost(evt);
            }
        });

        txtVehicleIdentificationNumber.setForeground(new java.awt.Color(204, 204, 204));
        txtVehicleIdentificationNumber.setText("format: 17 character");
        txtVehicleIdentificationNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVehicleIdentificationNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVehicleIdentificationNumberFocusLost(evt);
            }
        });
        txtVehicleIdentificationNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleIdentificationNumberActionPerformed(evt);
            }
        });

        txtDeviceSerialNumber.setForeground(new java.awt.Color(204, 204, 204));
        txtDeviceSerialNumber.setText("format: 10 digits");
        txtDeviceSerialNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDeviceSerialNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDeviceSerialNumberFocusLost(evt);
            }
        });
        txtDeviceSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeviceSerialNumberActionPerformed(evt);
            }
        });

        txtLinkedin.setForeground(new java.awt.Color(204, 204, 204));
        txtLinkedin.setText("example: https://www.linkedin.com/example");
        txtLinkedin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLinkedinFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLinkedinFocusLost(evt);
            }
        });
        txtLinkedin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedinActionPerformed(evt);
            }
        });

        txtMedicalno.setForeground(new java.awt.Color(204, 204, 204));
        txtMedicalno.setText("format: 7 digits");
        txtMedicalno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMedicalnoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMedicalnoFocusLost(evt);
            }
        });

        txtDeviceID.setForeground(new java.awt.Color(204, 204, 204));
        txtDeviceID.setText("format: XXXXXXXX-XXXXXXXX-XXXXXXXX-XXXXXXXX");
        txtDeviceID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDeviceIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDeviceIDFocusLost(evt);
            }
        });

        txtIP.setForeground(new java.awt.Color(204, 204, 204));
        txtIP.setText("example: 100.100.100.100");
        txtIP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIPFocusLost(evt);
            }
        });
        txtIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPActionPerformed(evt);
            }
        });

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblGeoData.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblGeoData.setText("GEOGRAPHICAL DATA");

        lblAddress2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAddress2.setText("Address Line 2 :");

        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCity.setText("City :");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        lblState.setText("State :");

        lblZip.setText("Zip Code :");

        txtZip.setForeground(new java.awt.Color(204, 204, 204));
        txtZip.setText("format: 5 digits");
        txtZip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtZipFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtZipFocusLost(evt);
            }
        });
        txtZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipActionPerformed(evt);
            }
        });

        lblBirthCertificate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBirthCertificate.setText("Birth Certificate Number :");

        txtLicense.setForeground(new java.awt.Color(204, 204, 204));
        txtLicense.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtLicense.setText("format: 9-11 Characters");
        txtLicense.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLicenseFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLicenseFocusLost(evt);
            }
        });

        txtBirthCertificate.setForeground(new java.awt.Color(204, 204, 204));
        txtBirthCertificate.setText("format: XXX-XX-XXXXXX");
        txtBirthCertificate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBirthCertificateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBirthCertificateFocusLost(evt);
            }
        });
        txtBirthCertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBirthCertificateActionPerformed(evt);
            }
        });

        lblVehicleIdentificationNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVehicleIdentificationNumber.setText("Vehicle Identification Number :");

        lblVehicleLicensePlate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVehicleLicensePlate.setText("Vehicle License Plate Number :");

        txtVehicleLicensePlate.setForeground(new java.awt.Color(204, 204, 204));
        txtVehicleLicensePlate.setText("format: 5-8 character");
        txtVehicleLicensePlate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVehicleLicensePlateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVehicleLicensePlateFocusLost(evt);
            }
        });
        txtVehicleLicensePlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleLicensePlateActionPerformed(evt);
            }
        });

        txtUniqueNumber.setForeground(new java.awt.Color(204, 204, 204));
        txtUniqueNumber.setText("format: 10 digits");
        txtUniqueNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUniqueNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUniqueNumberFocusLost(evt);
            }
        });
        txtUniqueNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUniqueNumberActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitle.setText("CREATE PROFILE");

        txtContactInfo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        txtContactInfo.setText("CONTACT DETAILS");

        lblPersonalDetails.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPersonalDetails.setText("PERSONAL DETAILS ");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("MEDICAL DETAILS");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("VEHICLE DETAILS");

        lblDeviceDetails.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblDeviceDetails.setText("DEVICE DETAILS");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setText("BIOMETRIC DETAILS");

        addPhoto.setText("Add Photo");
        addPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPhotoActionPerformed(evt);
            }
        });

        addFingerprints.setText("Add Fingerprints");
        addFingerprints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFingerprintsActionPerformed(evt);
            }
        });

        lblIp1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIp1.setText("IP Address :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator4)))
                .addGap(111, 111, 111))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblIp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDeviceSerialNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(lblDeviceId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(addPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(lblFingerPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addFingerprints, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDeviceSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblIp1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtDeviceID, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBirthCertificate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUniqueID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLinkedin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSsn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail)
                            .addComponent(txtLinkedin)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtBirthCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtUniqueNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblBankNo, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(lblLicense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDateofBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLicense)
                                    .addComponent(txtBankno, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txtDateofBirth, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFax)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblAddress1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(lblCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(lblState)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtState)
                                .addGap(21, 21, 21)
                                .addComponent(lblZip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblDeviceDetails)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator6)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator7))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPersonalDetails)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtContactInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2)
                                .addGap(3, 3, 3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMedicalNo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVehicleIdentificationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtMedicalno, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHealthNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHealthno, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtVehicleIdentificationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(lblVehicleLicensePlate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVehicleLicensePlate)))))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(397, 397, 397))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPersonalDetails)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSsn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDateofBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBirthCertificate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBirthCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBankNo)
                        .addComponent(txtBankno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUniqueID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtUniqueNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtContactInfo)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGeoData)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblState)
                    .addComponent(lblZip)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedicalno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedicalNo)
                    .addComponent(lblHealthNo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHealthno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicleIdentificationNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtVehicleIdentificationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVehicleLicensePlate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtVehicleLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDeviceDetails)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeviceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeviceId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeviceSerialNumber)
                    .addComponent(lblDeviceSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIp1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPhoto)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFingerPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addFingerprints, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel18)
                .addGap(3, 3, 3)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblFax, lblState, lblZip, txtAddress1, txtAddress2, txtBankno, txtBirthCertificate, txtCity, txtDateofBirth, txtDeviceID, txtDeviceSerialNumber, txtEmail, txtFax, txtHealthno, txtIP, txtLicense, txtLinkedin, txtMedicalno, txtName, txtSsn, txtState, txtVehicleIdentificationNumber, txtVehicleLicensePlate, txtZip, txtphoneNumber});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblBankNo, lblHealthNo, lblMedicalNo});

    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtFaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtVehicleIdentificationNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleIdentificationNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleIdentificationNumberActionPerformed

    private void txtDeviceSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeviceSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceSerialNumberActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        List list = this.isProfileValid();       
        if(profileFingerprints==null){
            list.add("Please provide Fingerprints!");
        }
        if(profilePhoto==null){
            list.add("Please provide Photo!");
        }
        if(!list.isEmpty()){
            JOptionPane.showMessageDialog(this, String.join("\n", list ), "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
        else{
 
            profile.setName(txtName.getText());
            profile.setAddressLine1(txtAddress1.getText());
            profile.setAddressLine2(txtAddress2.getText());
            profile.setCity(txtCity.getText());
            profile.setState(txtState.getText());
            profile.setZip(Integer.parseInt(txtZip.getText()));

           //DOB
            profile.setDateOfBirth(txtDateofBirth.getText());

            profile.setPhoneNumber(txtphoneNumber.getText());

            profile.setFaxNumber(txtFax.getText());

            profile.setEmailAddress(txtEmail.getText());

            profile.setSsn(txtSsn.getText());

            profile.setMedicalRecordNumber(Long.parseLong(txtMedicalno.getText()));

            profile.setHealthBeneficiaryNumber(txtHealthno.getText());

            profile.setBankAccountNumber(Long.parseLong(txtBankno.getText()));

            profile.setBirthCertificateNumber(txtBirthCertificate.getText());

            profile.setLicense_no(txtVehicleIdentificationNumber.getText());

            profile.setVehicleIdentificationNumber(txtVehicleIdentificationNumber.getText());

            profile.setVehicleLicensePlate(txtVehicleLicensePlate.getText());

            profile.setDeviceId(txtDeviceID.getText());

            profile.setDeviceSerialNumber(Long.parseLong(txtDeviceSerialNumber.getText()));

            profile.setLinkedin(txtLinkedin.getText());

            profile.setIp(txtIP.getText());

            profile.setBiometricFingerPrint(profileFingerprints);
            profile.setPhoto(profilePhoto);
            profile.setUniqueIdentifier(txtUniqueNumber.getText());
            profilePhoto=null;
            profileFingerprints=null;

            JOptionPane.showMessageDialog(this, "Profile is created.","Info",JOptionPane.INFORMATION_MESSAGE);

          
        }
          
        
        
//        profile.setAddress(txtAddress1.getText());
//        profile.setBank_no(txtBankno.getText());
//        profile.setBiometric_details(txtBiometric.getText());
//        profile.setCar_details(txtCarDetails.getText());
//        profile.setDate_of_birth(txtDateofBirth.getText());
//        profile.setDevice_details(txtDeviceID.getText());
//        profile.setEmail(txtEmail.getText());
//        profile.setFax(txtFax.getText());
//        profile.setHealth_no(txtHealthno.getText());
//        profile.setIp(txtIp.getText());
//        profile.setLicense_no(txtLicenseno.getText());
//        profile.setLinkedin(txtLinkedin.getText());
//        profile.setMedical_no(txtMedicalno.getText());
//        profile.setName(txtName.getText());
//        profile.setNumber(txtNumber.getText());
//        profile.setPhoto(txtPhoto.getText());
//        profile.setSsn(txtSsn.getText());
//        profile.setUnique_details(txtUniqueDetails.getText());
        
        
              

        
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipActionPerformed

    private void txtVehicleLicensePlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleLicensePlateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleLicensePlateActionPerformed

    private void txtUniqueNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUniqueNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniqueNumberActionPerformed

    private void txtDateofBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateofBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateofBirthActionPerformed

    private void txtphoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneNumberActionPerformed
        // TODO 
    }//GEN-LAST:event_txtphoneNumberActionPerformed

    private void txtphoneNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneNumberKeyPressed
      
    }//GEN-LAST:event_txtphoneNumberKeyPressed

    private void txtphoneNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneNumberKeyTyped
        // TODO add your handling code here:
    
    }//GEN-LAST:event_txtphoneNumberKeyTyped

    private void txtphoneNumberPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtphoneNumberPropertyChange
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_txtphoneNumberPropertyChange

    private void txtphoneNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtphoneNumberFocusLost
        // TODO add your handling code here:
        String phoneNumberText = txtphoneNumber.getText();
        String msg=Validation.validatePhoneNumber(phoneNumberText);
        if(msg!=null){
            JOptionPane.showMessageDialog(this, msg, "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
        if(Validation.isEmptyText(phoneNumberText)){
            txtphoneNumber.setText("format: (xxx)xxx-xxxx");
            txtphoneNumber.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtphoneNumberFocusLost

    private void txtphoneNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtphoneNumberFocusGained
       
        if(txtphoneNumber.getText().equals("format: (xxx)xxx-xxxx")){
            txtphoneNumber.setText("");
            txtphoneNumber.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtphoneNumberFocusGained

    private void txtSsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSsnActionPerformed

    private void txtBirthCertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBirthCertificateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBirthCertificateActionPerformed

    private void txtLinkedinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedinActionPerformed

    private void txtAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddress1ActionPerformed

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        String msg=Validation.validateName(txtName.getText());
        if(msg!=null){
            JOptionPane.showMessageDialog(this, msg, "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtNameFocusLost

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
      
    }//GEN-LAST:event_txtNameFocusGained

    private void txtFaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFaxFocusLost
        String textData = txtFax.getText();
        String msg=Validation.validateFaxNumber(textData);
        if(msg!=null){
            JOptionPane.showMessageDialog(this, msg, "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
        if(Validation.isEmptyText(textData)){
            txtFax.setText("format: (xxx)xxx-xxxx");
            txtFax.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtFaxFocusLost

    private void txtFaxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFaxFocusGained
        if(txtFax.getText().equals("format: (xxx)xxx-xxxx")){
            txtFax.setText("");
            txtFax.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtFaxFocusGained

    private void txtSsnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSsnFocusLost
        String txtData = txtSsn.getText();
        String msg = Validation.validateSsn(txtData);
        if(msg!=null){
            JOptionPane.showMessageDialog(this, msg, "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
        if(Validation.isEmptyText(txtData)){
            txtSsn.setText("format: XXX-XX-XXXX");
            txtSsn.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtSsnFocusLost

    private void txtSsnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSsnFocusGained
        
        if(txtSsn.getText().equals("format: XXX-XX-XXXX")){
            txtSsn.setText("");
        txtSsn.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtSsnFocusGained

    private void txtBirthCertificateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBirthCertificateFocusLost
        //format: 10-13 digits
        String txtData = txtBirthCertificate.getText();
        String msg = Validation.validateBirthCN(txtData);
        if(msg!=null){
            JOptionPane.showMessageDialog(this, msg, "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
        if(Validation.isEmptyText(txtData)){
            txtBirthCertificate.setText("format: XXX-XX-XXXXXX");
            txtBirthCertificate.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtBirthCertificateFocusLost

    private void txtBirthCertificateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBirthCertificateFocusGained
        if(txtBirthCertificate.getText().equals("format: XXX-XX-XXXXXX")){
            txtBirthCertificate.setText("");
        txtBirthCertificate.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtBirthCertificateFocusGained

    private void txtLicenseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLicenseFocusLost
        String txtData = txtLicense.getText();
        String msg = Validation.validateLicense(txtData);
        if(msg!=null){
            JOptionPane.showMessageDialog(this, msg, "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
        if(Validation.isEmptyText(txtData)){
            txtLicense.setText("format: 9-11 Characters");
            txtLicense.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtLicenseFocusLost

    private void txtLicenseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLicenseFocusGained
        if(txtLicense.getText().equals("format: 9-11 Characters")){
            txtLicense.setText("");
        txtLicense.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtLicenseFocusGained

    private void txtUniqueNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUniqueNumberFocusGained
        if(txtUniqueNumber.getText().equals("format: 10 digits")){
            txtUniqueNumber.setText("");
        txtUniqueNumber.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtUniqueNumberFocusGained

    private void txtUniqueNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUniqueNumberFocusLost
        String txtData = txtUniqueNumber.getText();
        String msg = Validation.validateUniqueID(txtData);
        if(msg!=null){
            JOptionPane.showMessageDialog(this, msg, "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
        if(Validation.isEmptyText(txtData)){
            txtUniqueNumber.setText("format: 10 digits");
            txtUniqueNumber.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtUniqueNumberFocusLost

    private void txtBanknoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBanknoFocusGained
        if(txtBankno.getText().equals("format: 10-13 digits")){
            txtBankno.setText("");
        txtBankno.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtBanknoFocusGained

    private void txtBanknoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBanknoFocusLost
        String txtData = txtBankno.getText();
        String msg = Validation.validateBankAc(txtData);
        if(msg!=null){
            JOptionPane.showMessageDialog(this, msg, "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
        if(Validation.isEmptyText(txtData)){
            txtBankno.setText("format: 10-13 digits");
            txtBankno.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtBanknoFocusLost

    private void txtLinkedinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLinkedinFocusGained
        if(txtLinkedin.getText().equals("example: https://www.linkedin.com/example")){
            txtLinkedin.setText("");
        txtLinkedin.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtLinkedinFocusGained

    private void txtLinkedinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLinkedinFocusLost
        String txtData = txtLinkedin.getText();
        String msg = Validation.validateLinkedIn(txtData);
        if(msg!=null){
            JOptionPane.showMessageDialog(this, msg, "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
        if(Validation.isEmptyText(txtData)){
            txtLinkedin.setText("example: https://www.linkedin.com/example");
            txtLinkedin.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtLinkedinFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        if(txtEmail.getText().equals("example: example@gmail.com")){
            txtEmail.setText("");
        txtEmail.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        String txtData = txtEmail.getText();
        String msg = Validation.validateEmailAddress(txtData);
        if(msg!=null){
            JOptionPane.showMessageDialog(this, msg, "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
        if(Validation.isEmptyText(txtData)){
            txtEmail.setText("example: example@gmail.com");
            txtEmail.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtZipFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtZipFocusGained
        if(txtZip.getText().equals("format: 5 digits")){
            txtZip.setText("");
        txtZip.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtZipFocusGained

    private void txtZipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtZipFocusLost
        String txtData = txtZip.getText();
        String msg = Validation.validateZipCode(txtData);
        if(msg!=null){
            JOptionPane.showMessageDialog(this, msg, "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
        if(Validation.isEmptyText(txtData)){
            txtZip.setText("format: 5 digits");
            txtZip.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtZipFocusLost

    private void txtMedicalnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMedicalnoFocusGained
        if(txtMedicalno.getText().equals("format: 7 digits")){
            txtMedicalno.setText("");
        txtMedicalno.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtMedicalnoFocusGained

    private void txtMedicalnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMedicalnoFocusLost
        String txtData = txtMedicalno.getText();
        String msg = Validation.validateMedicalRN(txtData);
        if(msg!=null){
            JOptionPane.showMessageDialog(this, msg, "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
        if(Validation.isEmptyText(txtData)){
            txtMedicalno.setText("format: 7 digits");
            txtMedicalno.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtMedicalnoFocusLost

    private void txtHealthnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHealthnoFocusGained
        if(txtHealthno.getText().equals("format: xxxx-xxx-xxxx")){
            txtHealthno.setText("");
        txtHealthno.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtHealthnoFocusGained

    private void txtHealthnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHealthnoFocusLost
        String txtData = txtHealthno.getText();
        String msg = Validation.validateHealthBN(txtData);
        if(msg!=null){
            JOptionPane.showMessageDialog(this, msg, "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
        if(Validation.isEmptyText(txtData)){
            txtHealthno.setText("format: xxxx-xxx-xxxx");
            txtHealthno.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtHealthnoFocusLost

    private void txtVehicleIdentificationNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVehicleIdentificationNumberFocusGained
        if(txtVehicleIdentificationNumber.getText().equals("format: 17 character")){
            txtVehicleIdentificationNumber.setText("");
        txtVehicleIdentificationNumber.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtVehicleIdentificationNumberFocusGained

    private void txtVehicleIdentificationNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVehicleIdentificationNumberFocusLost
        String txtData = txtVehicleIdentificationNumber.getText();
        String msg = Validation.validateVehicleIN(txtData);
        if(msg!=null){
            JOptionPane.showMessageDialog(this, msg, "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
        if(Validation.isEmptyText(txtData)){
            txtVehicleIdentificationNumber.setText("format: 17 character");
            txtVehicleIdentificationNumber.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtVehicleIdentificationNumberFocusLost

    private void txtVehicleLicensePlateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVehicleLicensePlateFocusGained
        if(txtVehicleLicensePlate.getText().equals("format: 5-8 character")){
            txtVehicleLicensePlate.setText("");
        txtVehicleLicensePlate.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtVehicleLicensePlateFocusGained

    private void txtVehicleLicensePlateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVehicleLicensePlateFocusLost
        String txtData = txtVehicleLicensePlate.getText();
        String msg = Validation.validateVehicleLP(txtData);
        if(msg!=null){
            JOptionPane.showMessageDialog(this, msg, "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
        if(Validation.isEmptyText(txtData)){
            txtVehicleLicensePlate.setText("format: 5-8 character");
            txtVehicleLicensePlate.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtVehicleLicensePlateFocusLost

    private void txtDeviceIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDeviceIDFocusGained
        if(txtDeviceID.getText().equals("format: XXXXXXXX-XXXXXXXX-XXXXXXXX-XXXXXXXX")){
            txtDeviceID.setText("");
        txtDeviceID.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtDeviceIDFocusGained

    private void txtDeviceIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDeviceIDFocusLost
        String txtData = txtDeviceID.getText();
        String msg = Validation.validateDeviceId(txtData);
        if(msg!=null){
            JOptionPane.showMessageDialog(this, msg, "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
        if(Validation.isEmptyText(txtData)){
            txtDeviceID.setText("format: XXXXXXXX-XXXXXXXX-XXXXXXXX-XXXXXXXX");
            txtDeviceID.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtDeviceIDFocusLost

    private void txtDeviceSerialNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDeviceSerialNumberFocusGained
        if(txtDeviceSerialNumber.getText().equals("format: 10 digits")){
            txtDeviceSerialNumber.setText("");
            txtDeviceSerialNumber.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtDeviceSerialNumberFocusGained

    private void txtDeviceSerialNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDeviceSerialNumberFocusLost
        String txtData = txtDeviceSerialNumber.getText();
        String msg = Validation.validateDeviceSN(txtData);
        if(msg!=null){
            JOptionPane.showMessageDialog(this, msg, "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
        if(Validation.isEmptyText(txtData)){
            txtDeviceSerialNumber.setText("format: 10 digits");
            txtDeviceSerialNumber.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtDeviceSerialNumberFocusLost

    private void txtIPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIPFocusGained
        if(txtIP.getText().equals("example: 100.100.100.100")){
            txtIP.setText("");
            txtIP.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtIPFocusGained

    private void txtIPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIPFocusLost
        String txtData = txtIP.getText();
        String msg = Validation.validateIp(txtData);
        if(msg!=null){
            JOptionPane.showMessageDialog(this, msg, "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
        if(Validation.isEmptyText(txtData)){
            txtIP.setText("example: 100.100.100.100");
            txtIP.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtIPFocusLost

    private void txtDateofBirthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateofBirthFocusGained
        if(txtDateofBirth.getText().equals("format: MM/DD/YYYY")){
            txtDateofBirth.setText("");
            txtDateofBirth.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_txtDateofBirthFocusGained

    private void txtDateofBirthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateofBirthFocusLost
        String txtData = txtDateofBirth.getText();
        String msg = Validation.validateDOB(txtData);
        if(msg!=null){
            JOptionPane.showMessageDialog(this, msg, "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
        if(Validation.isEmptyText(txtData)){
            txtDateofBirth.setText("format: MM/DD/YYYY");
            txtDateofBirth.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtDateofBirthFocusLost

    private void addPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPhotoActionPerformed
        String imagePath=getImagePath();
        if(imagePath==null){
            JOptionPane.showMessageDialog(this, "Please provide photo", "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
        profilePhoto=imagePath;
    }//GEN-LAST:event_addPhotoActionPerformed

    private void addFingerprintsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFingerprintsActionPerformed
        String imagePath=getImagePath();
        if(imagePath==null){
            JOptionPane.showMessageDialog(this, "Please provide fingerprints", "Incorrect Data", JOptionPane.ERROR_MESSAGE);
        }
       profileFingerprints=imagePath;
    }//GEN-LAST:event_addFingerprintsActionPerformed

    private void txtIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPActionPerformed
    
    private String getImagePath(){
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
        fc.setAcceptAllFileFilterUsed(false);
        fc.addChoosableFileFilter(filter);
        int result=fc.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = fc.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            return path;
        }
        return null;
    }
    
    private List isProfileValid(){
        List msg = new ArrayList();
        msg.add(Validation.validateName(txtName.getText()));
        msg.add(Validation.validateDOB(txtDateofBirth.getText()));
        msg.add(Validation.validateSsn(txtSsn.getText()));
        msg.add(Validation.validateBirthCN(txtBirthCertificate.getText()));
        msg.add(Validation.validateLicense(txtLicense.getText()));
        msg.add(Validation.validateUniqueID(txtUniqueNumber.getText()));
        msg.add(Validation.validateBankAc(txtBankno.getText()));
        msg.add(Validation.validateLinkedIn(txtLinkedin.getText()));
        msg.add(Validation.validatePhoneNumber(txtphoneNumber.getText()));
        msg.add(Validation.validateFaxNumber(txtFax.getText()));
        msg.add(Validation.validateEmailAddress(txtEmail.getText()));
        msg.add(Validation.validateMedicalRN(txtMedicalno.getText()));
        msg.add(Validation.validateHealthBN(txtHealthno.getText()));
        msg.add(Validation.validateVehicleIN(txtVehicleIdentificationNumber.getText()));
        msg.add(Validation.validateVehicleLP(txtVehicleLicensePlate.getText()));
        msg.add(Validation.validateDeviceId(txtDeviceID.getText()));
        msg.add(Validation.validateDeviceSN(txtDeviceSerialNumber.getText()));
        msg.add(Validation.validateIp(txtIP.getText()));
        msg.add(Validation.validateZipCode(txtZip.getText()));
        
        List diagMsg=new ArrayList();
        for(Object d:msg){
            if(d!=null){
                diagMsg.add(d);
            }
        }
        return diagMsg;
    }
    private String profilePhoto;
    private String profileFingerprints;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFingerprints;
    private javax.swing.JButton addPhoto;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblAddress2;
    private javax.swing.JLabel lblBankNo;
    private javax.swing.JLabel lblBirthCertificate;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDateofBirth;
    private javax.swing.JLabel lblDeviceDetails;
    private javax.swing.JLabel lblDeviceId;
    private javax.swing.JLabel lblDeviceSerialNumber;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblFingerPrint;
    private javax.swing.JLabel lblGeoData;
    private javax.swing.JLabel lblHealthNo;
    private javax.swing.JLabel lblIp;
    private javax.swing.JLabel lblIp1;
    private javax.swing.JLabel lblLicense;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblMedicalNo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblPersonalDetails;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUniqueID;
    private javax.swing.JLabel lblVehicleIdentificationNumber;
    private javax.swing.JLabel lblVehicleLicensePlate;
    private javax.swing.JLabel lblZip;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtBankno;
    private javax.swing.JTextField txtBirthCertificate;
    private javax.swing.JTextField txtCity;
    private javax.swing.JLabel txtContactInfo;
    private javax.swing.JTextField txtDateofBirth;
    private javax.swing.JTextField txtDeviceID;
    private javax.swing.JTextField txtDeviceSerialNumber;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtHealthno;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtLicense;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMedicalno;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtUniqueNumber;
    private javax.swing.JTextField txtVehicleIdentificationNumber;
    private javax.swing.JTextField txtVehicleLicensePlate;
    private javax.swing.JTextField txtZip;
    private javax.swing.JTextField txtphoneNumber;
    // End of variables declaration//GEN-END:variables
}
