/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Profile;
import validation.Validation;
import java.util.stream.Collectors;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author akshatajadhav
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    Profile profile;
    
    public ViewJPanel(Profile profile) {
        initComponents();
        this.profile = profile;
        displayProfile();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblAddress1 = new javax.swing.JLabel();
        lblMedicalNo = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        lblHealthNo = new javax.swing.JLabel();
        lblLicense = new javax.swing.JLabel();
        lblBankNo = new javax.swing.JLabel();
        lblDeviceSerialNumber = new javax.swing.JLabel();
        lblDeviceId = new javax.swing.JLabel();
        lblDateofBirth = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        lblFax = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblLinkedin = new javax.swing.JLabel();
        lblUniqueID = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtDateofBirth = new javax.swing.JTextField();
        txtAddress1 = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        txtphoneNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtBankno = new javax.swing.JTextField();
        txtSsn = new javax.swing.JTextField();
        txtHealthno = new javax.swing.JTextField();
        txtVehicleIdentificationNumber = new javax.swing.JTextField();
        txtDeviceSerialNumber = new javax.swing.JTextField();
        txtLinkedin = new javax.swing.JTextField();
        txtMedicalno = new javax.swing.JTextField();
        txtDeviceID = new javax.swing.JTextField();
        txtIP = new javax.swing.JTextField();
        lblGeoData = new javax.swing.JLabel();
        txtAddress2 = new javax.swing.JTextField();
        lblAddress2 = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        lblZip = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        lblBirthCertificate = new javax.swing.JLabel();
        txtLicense = new javax.swing.JTextField();
        txtBirthCertificate = new javax.swing.JTextField();
        lblVehicleIdentificationNumber = new javax.swing.JLabel();
        lblVehicleLicensePlate = new javax.swing.JLabel();
        txtVehicleLicensePlate = new javax.swing.JTextField();
        txtUniqueNumber = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txtContactInfo = new javax.swing.JLabel();
        lblPersonalDetails = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDeviceDetails = new javax.swing.JLabel();
        lblIp1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fingerPrintsLabel = new javax.swing.JLabel();
        photoLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setToolTipText("");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setEnabled(false);
        setPreferredSize(new java.awt.Dimension(1000, 800));

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("                                Name :");

        lblAddress1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAddress1.setText("Address Line 1 :");

        lblMedicalNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedicalNo.setText("Medical Record Number :");

        lblSsn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSsn.setText("Social Security Number :");

        lblHealthNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHealthNo.setText("Health Plan Beneficiary Number :");

        lblLicense.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLicense.setText("Driver's license Number :");

        lblBankNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBankNo.setText("Bank Account Number :");

        lblDeviceSerialNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDeviceSerialNumber.setText("Device Serial Number :");

        lblDeviceId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDeviceId.setText("Device ID :");

        lblDateofBirth.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDateofBirth.setText("Date of Birth :");

        lblNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumber.setText("Phone number :");

        lblFax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFax.setText("Fax Number :");

        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("Email Address :");

        lblLinkedin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLinkedin.setText("LinkedIn Profile :");

        lblUniqueID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUniqueID.setText("Unique Identification Number :");

        txtName.setEnabled(false);
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtDateofBirth.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDateofBirth.setToolTipText("");
        txtDateofBirth.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtDateofBirth.setEnabled(false);
        txtDateofBirth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDateofBirthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDateofBirthFocusLost(evt);
            }
        });
        txtDateofBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateofBirthActionPerformed(evt);
            }
        });

        txtAddress1.setEnabled(false);
        txtAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddress1ActionPerformed(evt);
            }
        });

        txtFax.setToolTipText("");
        txtFax.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtFax.setEnabled(false);
        txtFax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFaxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFaxFocusLost(evt);
            }
        });
        txtFax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxActionPerformed(evt);
            }
        });

        txtphoneNumber.setToolTipText("");
        txtphoneNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtphoneNumber.setEnabled(false);
        txtphoneNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtphoneNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtphoneNumberFocusLost(evt);
            }
        });
        txtphoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneNumberActionPerformed(evt);
            }
        });
        txtphoneNumber.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtphoneNumberPropertyChange(evt);
            }
        });
        txtphoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtphoneNumberKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtphoneNumberKeyTyped(evt);
            }
        });

        txtEmail.setToolTipText("");
        txtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtEmail.setEnabled(false);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtBankno.setToolTipText("");
        txtBankno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtBankno.setEnabled(false);
        txtBankno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBanknoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBanknoFocusLost(evt);
            }
        });

        txtSsn.setToolTipText("");
        txtSsn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtSsn.setEnabled(false);
        txtSsn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSsnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSsnFocusLost(evt);
            }
        });
        txtSsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSsnActionPerformed(evt);
            }
        });

        txtHealthno.setToolTipText("");
        txtHealthno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtHealthno.setEnabled(false);
        txtHealthno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHealthnoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHealthnoFocusLost(evt);
            }
        });

        txtVehicleIdentificationNumber.setToolTipText("");
        txtVehicleIdentificationNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtVehicleIdentificationNumber.setEnabled(false);
        txtVehicleIdentificationNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVehicleIdentificationNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVehicleIdentificationNumberFocusLost(evt);
            }
        });
        txtVehicleIdentificationNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleIdentificationNumberActionPerformed(evt);
            }
        });

        txtDeviceSerialNumber.setToolTipText("");
        txtDeviceSerialNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtDeviceSerialNumber.setEnabled(false);
        txtDeviceSerialNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDeviceSerialNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDeviceSerialNumberFocusLost(evt);
            }
        });
        txtDeviceSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeviceSerialNumberActionPerformed(evt);
            }
        });

        txtLinkedin.setToolTipText("");
        txtLinkedin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtLinkedin.setEnabled(false);
        txtLinkedin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLinkedinFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLinkedinFocusLost(evt);
            }
        });
        txtLinkedin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedinActionPerformed(evt);
            }
        });

        txtMedicalno.setToolTipText("");
        txtMedicalno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtMedicalno.setEnabled(false);
        txtMedicalno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMedicalnoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMedicalnoFocusLost(evt);
            }
        });

        txtDeviceID.setToolTipText("");
        txtDeviceID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtDeviceID.setEnabled(false);
        txtDeviceID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDeviceIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDeviceIDFocusLost(evt);
            }
        });

        txtIP.setToolTipText("");
        txtIP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtIP.setEnabled(false);
        txtIP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIPFocusLost(evt);
            }
        });

        lblGeoData.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblGeoData.setText("GEOGRAPHICAL DATA");

        txtAddress2.setEnabled(false);

        lblAddress2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAddress2.setText("Address Line 2 :");

        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCity.setText("City :");

        txtCity.setEnabled(false);
        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        lblState.setText("State :");

        txtState.setEnabled(false);

        lblZip.setText("Zip Code :");

        txtZip.setToolTipText("");
        txtZip.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtZip.setEnabled(false);
        txtZip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtZipFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtZipFocusLost(evt);
            }
        });
        txtZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipActionPerformed(evt);
            }
        });

        lblBirthCertificate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBirthCertificate.setText("Birth Certificate Number :");

        txtLicense.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtLicense.setToolTipText("");
        txtLicense.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtLicense.setEnabled(false);
        txtLicense.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLicenseFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLicenseFocusLost(evt);
            }
        });

        txtBirthCertificate.setToolTipText("");
        txtBirthCertificate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtBirthCertificate.setEnabled(false);
        txtBirthCertificate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBirthCertificateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBirthCertificateFocusLost(evt);
            }
        });
        txtBirthCertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBirthCertificateActionPerformed(evt);
            }
        });

        lblVehicleIdentificationNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVehicleIdentificationNumber.setText("Vehicle Identification Number :");

        lblVehicleLicensePlate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVehicleLicensePlate.setText("Vehicle License Plate Number :");

        txtVehicleLicensePlate.setToolTipText("");
        txtVehicleLicensePlate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtVehicleLicensePlate.setEnabled(false);
        txtVehicleLicensePlate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVehicleLicensePlateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVehicleLicensePlateFocusLost(evt);
            }
        });
        txtVehicleLicensePlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleLicensePlateActionPerformed(evt);
            }
        });

        txtUniqueNumber.setToolTipText("");
        txtUniqueNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtUniqueNumber.setEnabled(false);
        txtUniqueNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUniqueNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUniqueNumberFocusLost(evt);
            }
        });
        txtUniqueNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUniqueNumberActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitle.setText("            PROFILE");

        txtContactInfo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        txtContactInfo.setText("CONTACT DETAILS");

        lblPersonalDetails.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPersonalDetails.setText("PERSONAL DETAILS ");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("MEDICAL DETAILS");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("VEHICLE DETAILS");

        lblDeviceDetails.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblDeviceDetails.setText("DEVICE DETAILS");

        lblIp1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIp1.setText("IP Address :");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Photo");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fingerprints");

        fingerPrintsLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        photoLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(photoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fingerPrintsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fingerPrintsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator4)))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblDeviceSerialNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDeviceId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblVehicleIdentificationNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAddress1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAddress2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblMedicalNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblIp1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIP, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDeviceSerialNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblState)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblZip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addComponent(txtDeviceID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAddress1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAddress2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblVehicleLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblHealthNo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHealthno, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVehicleLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBirthCertificate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUniqueID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLinkedin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSsn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLinkedin, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtUniqueNumber)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblBankNo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSsn)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtBirthCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblDateofBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblLicense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDateofBirth)
                                    .addComponent(txtBankno)
                                    .addComponent(txtLicense, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFax)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(356, 356, 356)
                                .addComponent(lblTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMedicalno)
                                    .addComponent(txtVehicleIdentificationNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator5)
                                .addGap(0, 0, 0))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDeviceDetails)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPersonalDetails)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtContactInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2)
                                .addGap(3, 3, 3)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPersonalDetails)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSsn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDateofBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLicense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBirthCertificate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBirthCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBankNo)
                            .addComponent(txtBankno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUniqueNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUniqueID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLinkedin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtContactInfo)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFax))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGeoData)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddress1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddress2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddress2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCity)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblZip)
                                .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblState)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMedicalno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMedicalNo)
                            .addComponent(lblHealthNo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHealthno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVehicleIdentificationNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtVehicleIdentificationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVehicleLicensePlate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtVehicleLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDeviceDetails)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDeviceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDeviceId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDeviceSerialNumber)
                            .addComponent(lblDeviceSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIp1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel19)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblFax, lblState, lblZip, txtAddress1, txtAddress2, txtBankno, txtBirthCertificate, txtCity, txtDateofBirth, txtDeviceID, txtDeviceSerialNumber, txtEmail, txtFax, txtHealthno, txtIP, txtLicense, txtLinkedin, txtMedicalno, txtName, txtSsn, txtState, txtVehicleIdentificationNumber, txtVehicleLicensePlate, txtZip, txtphoneNumber});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblBankNo, lblHealthNo, lblMedicalNo});

    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtFaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtVehicleIdentificationNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleIdentificationNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleIdentificationNumberActionPerformed

    private void txtDeviceSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeviceSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceSerialNumberActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipActionPerformed

    private void txtVehicleLicensePlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleLicensePlateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleLicensePlateActionPerformed

    private void txtUniqueNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUniqueNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniqueNumberActionPerformed

    private void txtDateofBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateofBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateofBirthActionPerformed

    private void txtphoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneNumberActionPerformed
        // TODO 
    }//GEN-LAST:event_txtphoneNumberActionPerformed

    private void txtphoneNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneNumberKeyPressed
      
    }//GEN-LAST:event_txtphoneNumberKeyPressed

    private void txtphoneNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneNumberKeyTyped
        // TODO add your handling code here:
    
    }//GEN-LAST:event_txtphoneNumberKeyTyped

    private void txtphoneNumberPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtphoneNumberPropertyChange
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_txtphoneNumberPropertyChange

    private void txtphoneNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtphoneNumberFocusLost
        
    }//GEN-LAST:event_txtphoneNumberFocusLost

    private void txtphoneNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtphoneNumberFocusGained
       
    }//GEN-LAST:event_txtphoneNumberFocusGained

    private void txtSsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSsnActionPerformed

    private void txtBirthCertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBirthCertificateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBirthCertificateActionPerformed

    private void txtLinkedinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedinActionPerformed

    private void txtAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddress1ActionPerformed

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        
    }//GEN-LAST:event_txtNameFocusLost

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
      
    }//GEN-LAST:event_txtNameFocusGained

    private void txtFaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFaxFocusLost
        
    }//GEN-LAST:event_txtFaxFocusLost

    private void txtFaxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFaxFocusGained
        
    }//GEN-LAST:event_txtFaxFocusGained

    private void txtSsnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSsnFocusLost
        
    }//GEN-LAST:event_txtSsnFocusLost

    private void txtSsnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSsnFocusGained
        
    }//GEN-LAST:event_txtSsnFocusGained

    private void txtBirthCertificateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBirthCertificateFocusLost
        
    }//GEN-LAST:event_txtBirthCertificateFocusLost

    private void txtBirthCertificateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBirthCertificateFocusGained
        
    }//GEN-LAST:event_txtBirthCertificateFocusGained

    private void txtLicenseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLicenseFocusLost
        
    }//GEN-LAST:event_txtLicenseFocusLost

    private void txtLicenseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLicenseFocusGained
        
    }//GEN-LAST:event_txtLicenseFocusGained

    private void txtUniqueNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUniqueNumberFocusGained
        
    }//GEN-LAST:event_txtUniqueNumberFocusGained

    private void txtUniqueNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUniqueNumberFocusLost
        
    }//GEN-LAST:event_txtUniqueNumberFocusLost

    private void txtBanknoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBanknoFocusGained
        
    }//GEN-LAST:event_txtBanknoFocusGained

    private void txtBanknoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBanknoFocusLost
        
    }//GEN-LAST:event_txtBanknoFocusLost

    private void txtLinkedinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLinkedinFocusGained
        
    }//GEN-LAST:event_txtLinkedinFocusGained

    private void txtLinkedinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLinkedinFocusLost
        
    }//GEN-LAST:event_txtLinkedinFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
       
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtZipFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtZipFocusGained
        
    }//GEN-LAST:event_txtZipFocusGained

    private void txtZipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtZipFocusLost
        
    }//GEN-LAST:event_txtZipFocusLost

    private void txtMedicalnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMedicalnoFocusGained
        
    }//GEN-LAST:event_txtMedicalnoFocusGained

    private void txtMedicalnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMedicalnoFocusLost
        
    }//GEN-LAST:event_txtMedicalnoFocusLost

    private void txtHealthnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHealthnoFocusGained
        
    }//GEN-LAST:event_txtHealthnoFocusGained

    private void txtHealthnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHealthnoFocusLost
        
    }//GEN-LAST:event_txtHealthnoFocusLost

    private void txtVehicleIdentificationNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVehicleIdentificationNumberFocusGained
        
    }//GEN-LAST:event_txtVehicleIdentificationNumberFocusGained

    private void txtVehicleIdentificationNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVehicleIdentificationNumberFocusLost
        
    }//GEN-LAST:event_txtVehicleIdentificationNumberFocusLost

    private void txtVehicleLicensePlateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVehicleLicensePlateFocusGained
        
    }//GEN-LAST:event_txtVehicleLicensePlateFocusGained

    private void txtVehicleLicensePlateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVehicleLicensePlateFocusLost
        
    }//GEN-LAST:event_txtVehicleLicensePlateFocusLost

    private void txtDeviceIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDeviceIDFocusGained
        
    }//GEN-LAST:event_txtDeviceIDFocusGained

    private void txtDeviceIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDeviceIDFocusLost
        
    }//GEN-LAST:event_txtDeviceIDFocusLost

    private void txtDeviceSerialNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDeviceSerialNumberFocusGained
        
    }//GEN-LAST:event_txtDeviceSerialNumberFocusGained

    private void txtDeviceSerialNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDeviceSerialNumberFocusLost
        
    }//GEN-LAST:event_txtDeviceSerialNumberFocusLost

    private void txtIPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIPFocusGained
        
    }//GEN-LAST:event_txtIPFocusGained

    private void txtIPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIPFocusLost
        
    }//GEN-LAST:event_txtIPFocusLost

    private void txtDateofBirthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateofBirthFocusGained
        
    }//GEN-LAST:event_txtDateofBirthFocusGained

    private void txtDateofBirthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateofBirthFocusLost
        
    }//GEN-LAST:event_txtDateofBirthFocusLost
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fingerPrintsLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblAddress2;
    private javax.swing.JLabel lblBankNo;
    private javax.swing.JLabel lblBirthCertificate;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDateofBirth;
    private javax.swing.JLabel lblDeviceDetails;
    private javax.swing.JLabel lblDeviceId;
    private javax.swing.JLabel lblDeviceSerialNumber;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblGeoData;
    private javax.swing.JLabel lblHealthNo;
    private javax.swing.JLabel lblIp1;
    private javax.swing.JLabel lblLicense;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblMedicalNo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblPersonalDetails;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUniqueID;
    private javax.swing.JLabel lblVehicleIdentificationNumber;
    private javax.swing.JLabel lblVehicleLicensePlate;
    private javax.swing.JLabel lblZip;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtBankno;
    private javax.swing.JTextField txtBirthCertificate;
    private javax.swing.JTextField txtCity;
    private javax.swing.JLabel txtContactInfo;
    private javax.swing.JTextField txtDateofBirth;
    private javax.swing.JTextField txtDeviceID;
    private javax.swing.JTextField txtDeviceSerialNumber;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtHealthno;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtLicense;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMedicalno;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtUniqueNumber;
    private javax.swing.JTextField txtVehicleIdentificationNumber;
    private javax.swing.JTextField txtVehicleLicensePlate;
    private javax.swing.JTextField txtZip;
    private javax.swing.JTextField txtphoneNumber;
    // End of variables declaration//GEN-END:variables

    private void displayProfile() {
        txtName.setText(profile.getName());
        txtSsn.setText(profile.getSsn());
        if(profile.getDateOfBirth()!=null){
            txtDateofBirth.setText((new SimpleDateFormat("MM/dd/yyyy")).format(profile.getDateOfBirth()));
        }
        txtBirthCertificate.setText(profile.getBirthCertificateNumber());
        txtLicense.setText(profile.getLicense_no());
        txtUniqueNumber.setText(profile.getUniqueIdentifier());
        txtBankno.setText(Long.toString(profile.getBankAccountNumber()));
        txtLinkedin.setText(profile.getLinkedin());
        txtphoneNumber.setText(profile.getPhoneNumber());
        txtFax.setText(profile.getFaxNumber());
        txtEmail.setText(profile.getEmailAddress());
        txtAddress1.setText(profile.getAddressLine1());
        txtAddress2.setText(profile.getAddressLine2());
        txtCity.setText(profile.getCity());
        txtState.setText(profile.getState());
        txtZip.setText(Long.toString(profile.getZip()));
        txtMedicalno.setText(Long.toString(profile.getMedicalRecordNumber()));
        txtHealthno.setText(profile.getHealthBeneficiaryNumber());
        txtVehicleIdentificationNumber.setText(profile.getVehicleIdentificationNumber());
        txtVehicleLicensePlate.setText(profile.getVehicleLicensePlate());
        txtDeviceID.setText(profile.getDeviceId());
        txtDeviceSerialNumber.setText(Long.toString(profile.getDeviceSerialNumber()));
        txtIP.setText(profile.getIp());
        ImageIcon photoIcon=new ImageIcon(profile.getPhoto());
        Image si=photoIcon.getImage().getScaledInstance(206,250,Image.SCALE_DEFAULT);
        photoIcon=new ImageIcon(si);
        photoLabel.setIcon(photoIcon);
        ImageIcon fingerprintIcon=new ImageIcon(profile.getBiometricFingerPrint());
        Image si1=fingerprintIcon.getImage().getScaledInstance(206,250,Image.SCALE_DEFAULT);
        fingerprintIcon=new ImageIcon(si1);
        fingerPrintsLabel.setIcon(fingerprintIcon);
        
    }
}
